sudo: required

services: 
  - docker

before_install: 
  - docker build -t lostark78/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lostark78/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  environment: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-123531314423"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
